### PR TITLE
Loop over all subdirectories of the temporary directory.  Some packages,

### PR DESCRIPTION
**Pull request by senorhubris**
when unpacked, have more than one directory at the top level.

### CODE REVIEW

**Comment by senorhubris** [comment]
I have seen a few instances where packages have more than one directory within them at the top level.  This caused 'glob' to return a list of more than one thing.  In turn, this caused the code to fail because 'pushd' was passed multiple arguments.

**Comment by oalders** [comment]
Thanks!  Would you be able to provide a test for this? You could inject a tarball from CPAN, like is done in `inject_module()` in `t/06_inject_live.t`.

**Comment by senorhubris** [comment]
I'll see what I can do.

**Comment by senorhubris** [comment]
I've investigated this further. I couldn't understand why I was seeing this on one machine but not on a different machine.  The machine with the issue was also *very* slow to index.  

I updated the following packages to the latest: IO::Uncompress::Gunzip, IO::Zlib, Moo, Archive::Tar, Archive::Extract

and now performance is as expected and the issue this PR fixes no longer exists.  Unfortunately I have no idea which package fixed the issue. 

Not many of the requirements in the cpanfile have versions.  If I figure out what package and which version of that package causes this issue I'll submit a patch to fix that.  

This PR can be closed.

**Comment by oalders** [comment]
Thanks for this.  Having more minimum version numbers sounds like a good idea.

**Pull request closed without merging**
