### PR TITLE
Add 'extra_path' option to cli injector and use it in the injector to

### PR DESCRIPTION
**Pull request by senorhubris**
add extra path elements following the author.

### CODE REVIEW

**Comment by senorhubris** [comment]
I think this is a better approach than my previous PR (PR #39 )

**Comment by oalders** [comment]
Thanks very much for this!

**Comment by oalders** [comment]
@senorhubris would be able to send a PR with a doc patch for this?  Also, I wonder if `author_subdir` would be a little clearer than `extra_path` here?

**Comment by senorhubris** [comment]
I can do both those.  Not a problem.

**Pull request merged**
